{
	"version": 1695098327,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/roket-sheet0.png",
		"images/particles.png",
		"images/object-sheet0.png",
		"images/laser-sheet0.png",
		"images/batu-sheet0.png",
		"images/batu-sheet1.png",
		"images/particles2.png",
		"images/bakcgroundgame.png",
		"images/start-sheet0.png",
		"images/next-sheet0.png",
		"images/exit-sheet0.png",
		"images/soal1-sheet0.png",
		"images/soal2-sheet0.png",
		"images/soal3-sheet0.png",
		"images/soal4-sheet0.png",
		"images/soal5-sheet0.png",
		"images/soal6-sheet0.png",
		"images/soal7-sheet0.png",
		"images/soal8-sheet0.png",
		"images/loadingmerah-sheet0.png",
		"images/loadingmerah-sheet1.png",
		"images/loadingmerah-sheet2.png",
		"images/loadingmerah-sheet3.png",
		"images/loadingmerah-sheet4.png",
		"images/gameover-sheet0.png",
		"images/playgameover-sheet0.png",
		"images/youwin-sheet0.png",
		"images/info-sheet0.png",
		"images/layoutinfo-sheet0.png",
		"images/benar-sheet0.png",
		"images/salah-sheet0.png",
		"images/stick-sheet0.png",
		"images/tujuan-sheet0.png",
		"images/majutujuan-sheet0.png",
		"images/mundurtujuan-sheet0.png",
		"images/tmblhomecaramain-sheet0.png",
		"media/laser-gun-72558.ogg",
		"media/laser one shot.ogg",
		"media/rock-destroy-6409.ogg",
		"media/sound effect bunyi ledakan [tuberipper.com].ogg",
		"media/buzzer-or-wrong-answer-20582.ogg",
		"media/ping-82822.ogg",
		"media/space war - retro shooter [android] gameplay [tuberipper.com].ogg",
		"media/space war intro [tuberipper.com].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"bumper pembatik final.webm"
	]
}